spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/iyilik_sepeti
    username: postgres
    password: asel.02
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: 8080

app:
  jwt:
    secret: e49836f2f046ce141ec161ad3fe061e6
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
