spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/iyilik_sepeti
    username: postgres
    password: asel.02
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB

app:
  jwt:
    secret: e49836f2f046ce141ec161ad3fe061e6
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.donatecommerce: DEBUG
# Import API Configurations
import:
  api:
    fakestore:
      url: https://fakestoreapi.com
    dummyjson:
      url: https://dummyjson.com